### PR TITLE
Added all email vars and color and font settings vars

### PR DESCRIPTION
**Pull request by TheWebTech**
I have not tested locally, didn't really know how.

I followed the format you were using though so it should be good.
@williamspiro 

Addresses part of #11

### CODE REVIEW

**Comment by TheWebTech** [comment]
still can't figure out how to test properly, guessing I need to do like we do with the chrome extension, load the dev folder as an extension into vs code. I'll try to figure that out.

In the mean time though I'm finding a lot of the functionality that was added doesn't work for me #19 , so I might have something wrong in my settings or something.

Until that's figured out I probably can't test accurately

**Comment by TheWebTech** [comment]
figured out how to test.

it appears the things I added are working.
I am getting this error though:

> [WilliamSpiro.hubl]: One or more snippets from the extension 'hubl' very likely confuse snippet-variables and snippet-placeholders (see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details)

**Comment by williamspiro** [comment]
Hm weird in the live version I am having the same issue on some snippets, but they all work locally. I am going to merge and deploy and see if that fixes things. 

Thanks @TheWebTech !!

**Comment by beacondigitalmarketing** [comment]
@williamspiro, that error has been persistent.  Noticed it when i first cloned.  Have not seen a negative impact on anything, though

**Pull request merged**
